### ISSUE TITLE
Not C89 compliant

### ISSUE THREAD

**Issue by jddurand** [jeffreykegler/libmarpa#119] opened 2022-07-28 06:41 UTC
Latest version of libmarpa fails to compile on old MSVC compilers, maybe because having instructions before declarations? C.f. https://ci.appveyor.com/project/jddurand/c-marpawrapper/builds/44302583 and click on lines having a red mark.
This is is blocking a new version of c-marpaWrapper.

**Comment by jeffreykegler** [comment] 2022-07-28 16:38
I looked at https://ci.appveyor.com/project/jddurand/c-marpawrapper/builds/44302583/job/rplbbm7ft1npxypf#L569 .  To reliably match the error messages to my code, I'll need a release tag or a commit.

**Comment by jddurand** [comment] 2022-07-28 16:57
Indded, my issue is confusing because I created it under libmarpa _BUT_ the source of libmarpa that I used is the one of Marpa--R2, latest commit of master branch... If you know how to get which revision of libmarpa correspond to latest commit under Marpa--R2's master branch then you're done

**Comment by jddurand** [comment] 2022-07-28 16:58
https://github.com/jeffreykegler/Marpa--R2/blame/master/cpan/engine/read_only/marpa.c#L16709 is the line on which it fails, presumably because of previous error (?)

**Comment by jeffreykegler** [comment] 2022-07-28 17:19
In every autoconf distribution, I include a `git log` output listing the last 5 commits: https://github.com/jeffreykegler/Marpa--R2/blob/master/cpan/engine/read_only/GIT_LOG.txt.

**Comment by jddurand** [comment] 2022-07-28 18:08
Here it is: https://github.com/jddurand/c-marpaWrapper/blob/master/3rdparty/github/Marpa--R2/cpan/engine/read_only/GIT_LOG.txt

**Comment by jeffreykegler** [comment] 2022-07-28 18:21
The C89 non-conformance at https://github.com/jeffreykegler/Marpa--R2/blame/master/cpan/engine/read_only/marpa.c#L16709 has been fixed in later commits, including the one in the current `tested` branch.  (My `master` branch sometimes contains "broken" versions, so I have a "tested" branch that contains a version which passes testing.)  Does that provide what you need?

**Comment by jeffreykegler** [comment] 2022-07-28 18:56
I do not do "official" releases of Libmarpa yet, and I don't plan any new releases of Marpa::R2, but I could produce a tested Libmarpa version that is tagged with a "development" release number, if that would be helpful.

**Comment by jddurand** [comment] 2022-07-29 03:44
There is no ```tested``` branch on the remote repository. I see ```master```, ```trial```, ```testing```, ```lastrc```, ```bugfix```, ```rc``` and ```travis```. Can you push it to remote. Or shall I checkout explicitely the tag of the latest R2 release instead, i.e. ```Marpa-R2-10.000000```.

**Comment by jddurand** [comment] 2022-07-29 04:03
In the meantime I will look how I can work directly with the tested branch libmarpa -;)

**Comment by jddurand** [comment] 2022-07-29 06:24
I have tested using generation of libmarpa under the ```tested``` branch:

- The definition of the alignof() macro do not work under MSVC compiler (cl), c.f. https://ci.appveyor.com/project/jddurand/c-marpawrapper/builds/44314087/job/wi59x5qejh087md6
-- The fix is simply to put that on a single line, e.g. https://github.com/jddurand/c-marpaWrapper/commit/43a0e5e686b42b047cee077067e9678ba117711c
- The macro alignof() is defined twice in the generated file marpa_ami.h
- This is still not compiling under old version of cl, c.f. https://ci.appveyor.com/project/jddurand/c-marpawrapper/build/job/5kir8kpquraihd58

I will remove the "#line" lines today in the generated files to identify the root cause, eventually.

**Comment by jddurand** [comment] 2022-07-29 09:04
Ok, so I am glad to say that I got it compiling with old versions of cl, using the following fixes, that I did in the generated source but should be ported to the .w:

- alignof() macro must be done on a single line. C.f. https://github.com/jddurand/c-marpaWrapper/commit/43a0e5e686b42b047cee077067e9678ba117711c. Take care that it is defined twice in at least marpa_ami.h
- The MARPA_OFF_DEBUGx macros, when they are no-op, are called nevertheless with a remaining comma ```;``` but old compilers do not like when there no statement before ```;```. I suggest to put the comma in the macro definitions and remove it from the macro invocations. C.f. https://github.com/jddurand/c-marpaWrapper/commit/68bd5ff9093b054b5b1a029223052ea74e001d81 for the invocations.
- One call to MARPA_OFF_DEBUG3() is wrong: not enough parameters. C.f. https://github.com/jddurand/c-marpaWrapper/commit/94e49697f283a47b030ff3746a790a3116ff3b40 .

**Comment by jeffreykegler** [comment] 2022-07-29 14:32
@jddurand:  Good work!  Yes, while Libmarpa was made a separate repo in order to allow non-Marpa::R2 uses of the core C code, it remained heavily tied into Marpa::R2, and for a long time the practical way to grab a copy of the distribution has been to pull it from Marpa::R2.

I am gradually getting Libmarpa to stand on its own, and now (and, I hope, going forward) the best way to grab a distribution is from the Libmarpa repo itself.

I will take the changes upstream, and update the "tested" branch.  What's the best way to test for MSVC in the pre-processor?  `#if defined(_MSC_VER)`?

**Comment by jddurand** [comment] 2022-07-29 14:48
Yes, testing testing the MSVC compiler can be safely done like that, c.f. https://blog.kowalczyk.info/article/j/guide-to-predefined-macros-in-c-compilers-gcc-clang-msvc-etc..html for a nice page that I recommand for bookmarks ;)

Nevertheless, IMHO, I am not sure you have to do something specific for this compiler - it just appears that this is the one I used to spot these issues.

**Comment by jeffreykegler** [comment] 2022-07-29 14:51
@jddurand Re the `MARPA_OFF_DEBUG` macros, can I assume the problem is only when they are followed by a declaration?  The older compiler would be correct in that case, because a declaration following an empty statement *is* a declaration.

On the other hand, any C compiler should allow an empty statement anywhere a statement is allowed, so I have to think the empty statement is OK if not followed by a declaration.

**Comment by jddurand** [comment] 2022-07-29 14:59
> @jddurand Re the `MARPA_OFF_DEBUG` macros, can I assume the problem is only when they are followed by a declaration? The older compiler would be correct in that case, because a declaration following an empty statement _is_ a declaration.
> 
> On the other hand, any C compiler should allow an empty statement anywhere a statement is allowed, so I have to think the empty statement is OK if not followed by a declaration.

Probably... I think these compilers implement K&R instead of C89 - if is this is valid in K&R it should do it. I do not have such a compiler under my hands, but this can fortunately be validated using Appveyor, that I use to validate my code for a lot of compilers on Windows.

**Comment by jeffreykegler** [comment] 2022-07-29 15:01
Btw, is Appveyor free for open source?  Or must it be paid for?

**Comment by jddurand** [comment] 2022-07-29 15:03
> * The MARPA_OFF_DEBUGx macros, when they are no-op, are called nevertheless with a remaining comma `;` but old compilers do not like when there is no statement before `;`.  etc...
As per your previous comment, the root cause is probably because (quoted) "empty statement is OK if not followed by a declaration"

**Comment by jddurand** [comment] 2022-07-29 15:08
> Btw, is Appveyor free for open source? Or must it be paid for?

Free for an open source project. You can even use your github account to log into Appveyor. This is quite an advanced CI/CD thingy, and oh god, so good to have something that do think Linux only... I configured it to upload automatically windows packages/executables back to github when I do a release, very very useful.... for example: https://github.com/jddurand/c-marpaWrapper/releases , see all these *.exe file ? Uploaded automatically by AppVeyor.

**Comment by jeffreykegler** [comment] 2022-07-29 16:38
@jddurand I took a first stab at upstreaming the fixes in commit bb79482cf17aeae0bc6f7109ab8dd6e02e3834f0.  Currently, the head of the "tested" branch is at this commit.  Let me know if there are any problems.

**Comment by jddurand** [comment] 2022-07-29 18:58
> @jddurand I took a first stab at upstreaming the fixes in commit [bb79482](https://github.com/jeffreykegler/libmarpa/commit/bb79482cf17aeae0bc6f7109ab8dd6e02e3834f0). Currently, the head of the "tested" branch is at this commit. Let me know if there are any problems.

@jeffreykegler I confirm it is compiling fine from VS2008 up to VS2022, many many thanks.
For the record I tested also with gcc and clang on my Linux box, all is well also.

Do we agree that I continue to consider the 'tested' branch of libmarpa as the reference branch from which I should do updates in the future ?

I can now work on other optimizations I had in mind, with a new release of c-marpaESLIF soon.

**Comment by jeffreykegler** [comment] 2022-07-30 15:23
@jddurand: Yes, taking future updates from the "tested" branch is what I recommend for now.  In the future, Libmarpa will have "official" tagged releases, and at that point you may prefer those.

Per https://github.com/jeffreykegler/libmarpa/issues/119#issuecomment-1199857515, this issue is fixed.  Absent feedback to the contrary, I will close this issue after a couple of days.

**Comment by jeffreykegler** [comment] 2022-08-02 15:59
Closed per https://github.com/jeffreykegler/libmarpa/issues/119#issuecomment-1200225073.

**Closed by jeffreykegler** 2022-08-02 15:59 UTC
Labels: About to be closed
