### ISSUE TITLE
Unable to run test suite

### ISSUE THREAD

**Issue by mpope9** [jeffreykegler/libmarpa#110] opened 2022-05-21 03:12 UTC
I'm trying to run the test suite with
```bash
make test
```

And I see the following error:
```
...
[100%] Linking C static library libmarpa_s.a
/usr/bin/cmake -P CMakeFiles/marpa_s.dir/cmake_clean_target.cmake
/usr/bin/cmake -E cmake_link_script CMakeFiles/marpa_s.dir/link.txt --verbose=1
/usr/bin/ar qc libmarpa_s.a CMakeFiles/marpa_s.dir/marpa.c.o CMakeFiles/marpa_s.dir/marpa_tavl.c.o CMakeFiles/marpa_s.dir/marpa_ami.c.o CMakeFiles/marpa_s.dir/marpa_obs.c.o CMakeFiles/marpa_s.dir/marpa_avl.c.o
/usr/bin/ranlib libmarpa_s.a
make[3]: Leaving directory '/home/pope/projects/libmarpa/cm_build'
[100%] Built target marpa_s
make[2]: Leaving directory '/home/pope/projects/libmarpa/cm_build'
/usr/bin/cmake -E cmake_progress_start /home/pope/projects/libmarpa/cm_build/CMakeFiles 0
make  -f CMakeFiles/Makefile2 preinstall
make[2]: Entering directory '/home/pope/projects/libmarpa/cm_build'
make[2]: Nothing to be done for 'preinstall'.
make[2]: Leaving directory '/home/pope/projects/libmarpa/cm_build'
Install the project...
/usr/bin/cmake -P cmake_install.cmake
-- Install configuration: "Debug"
-- Installing: ../test/usr/local/lib/libmarpa.so
-- Installing: ../test/usr/local/lib/libmarpa_s.a
-- Installing: ../test/usr/local/include/marpa.h
-- Installing: ../test/usr/local/lib/pkgconfig/libmarpa.pc
make[1]: Leaving directory '/home/pope/projects/libmarpa/cm_build'
# Shares a directory with the cm_build time stamp
rm timestamp/cm_build.stamp
rm: cannot remove 'timestamp/cm_build.stamp': No such file or directory
make: [Makefile:102: timestamp/cm_debug.stamp] Error 1 (ignored)
date > timestamp/cm_debug.stamp
Updating cm_debug time stamp: Sat May 21 03:10:10 AM UTC 2022
test Out of date wrt cm_debug
rm -rf do_test
mkdir do_test
cd do_test && cmake ../test
CMake Warning (dev) in CMakeLists.txt:
  No project() command is present.  The top-level CMakeLists.txt file must
  contain a literal, direct call to the project() command.  Add a line of
  code such as

    project(ProjectName)

  near the top of the file, but after cmake_minimum_required().

  CMake is pretending there is a "project(Project)" command on the first
  line.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at CMakeLists.txt:16 (message):
  /home/pope/projects/libmarpa/test vs.  /home/pope/projects/libmarpa/test:
  In-source builds are not allowed.


-- CMAKE_BUILD_TYPE=""
-- Configuring incomplete, errors occurred!
See also "/home/pope/projects/libmarpa/test/CMakeFiles/CMakeOutput.log".
make: *** [Makefile:116: timestamp/test.stamp] Error 1
```

Am I missing a setup command?

**Comment by jeffreykegler** [comment] 2022-05-21 14:49
I've never seen this symptom ("No project() command is present") and have not been able to duplicate it.  What version or commit are you using?

**Comment by mpope9** [comment] 2022-05-21 15:51
I'm at commit 873925968ef2909a4490fbcaf86eb07c8b193766. Was able to make + make install, if that helps. On Ubuntu.

BTW working on this Dockerfile to assist me in the process:
```dockerfile
# syntax=docker/dockerfile:1
FROM ubuntu:18.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update -y -q && \
    apt upgrade -y -q && \
    apt install -y -q \
        build-essential \
        texlive-full \
        texlive-base \
        texlive-binaries \
        texlive-latex-extra \
        texlive-fonts-recommended \
        texinfo \
        emacs \
        autoconf \
        libtool \
        cmake

COPY . /app
RUN make -C /app dist
WORKDIR /app/ac_dist
RUN make
```

Any interest in a PR once I get it working?

**Comment by jeffreykegler** [comment] 2022-05-21 15:58
Yes, I'd like to see the PR, though what I often do is an "ours" merge (to track the credit for the ideas) and then redo it entirely.  For example, I might covert a script into a "HOW TO" document.

**Comment by jeffreykegler** [comment] 2022-05-21 16:10
I might be having problems with Perl one-liners in the Makefiles not being nearly as portable as I'd hoped.  @dabrahams is having problems which seem to be caused by these.  Unless I have a more attractive idea, my next step will be to convert all these Perl one-liners to `sed`, whose portability has strong support in the standards.  I've already done some of these conversions, and they did make problems go away.

**Comment by mpope9** [comment] 2022-05-21 16:33
Makes sense. Thanks.
Follow up question: is there a way to build without the docs? The docs are why all the tex deps are required, if I understand this correctly?

**Comment by jeffreykegler** [comment] 2022-05-21 16:37
There is currently no way to build w/o the docs, and even if I added one, the TeX dependencies would remain. The source code is in CWeb, Knuth's TeX-based literate programming system, so the source code requires TeX.

Sent with [ProtonMail](https://protonmail.com/) secure email.

------- Original Message -------

**Comment by jeffreykegler** [comment] 2022-05-21 20:31
@mpope9 -- to explain your choices here:

Note there are two kinds of building of Libmarpa: source-code-developer and packaging-developer.  The source-code developers must clone the repo, and install a bunch of complex supporting software.  In return they can hack the source, and have some testing available.

A "packaging developer" need only install either the autoconf or CMake distribution.  I plan, in the near future, to allow some minimal testing in the CMake distro.  Neither the autoconf or CMake distribution requires TeX or CWeb.  Both compile from .c files, which are *not* the source.

The CWeb has proved a life-saver, because it enables the Libmarpa engine to have a very detailed, nicely formatted and well-indexed commentary, which allows math notation.  It's an obstacle to collaborators, but given the mathematical nature of the source, very few collaborators want deal with it.  So I have paid a price for CWeb, but I think it's been worth it.

Why is the testing in Libmarpa so minimal?  The answer is that its origin is as a C code for use inside Marpa::R2, which does have a very extensive test suite.  I decided early on not to completely entangle the C library (Libmarpa) in Perl, letting a low-level library be completely separate so that, in principle, other interfaces could be written using it.

The low-level nature of Libmarpa makes it very flexible -- there is almost no trace of its origin inside Perl XS.  The disadvantage is that any really thorough test suite, as a practical matter, would require a higher level wrapper.

@dabrahams -- this comment might be of interest to you.

**Comment by mpope9** [comment] 2022-05-21 20:48
Makes sense. I'll probably explore the package maintainer route when I have a full handle on things. Feel free to close this issue, since it looks like the previous one is tracking a similar issue.

**Comment by jeffreykegler** [comment] 2022-05-21 22:37
@mpope9 I do not want to close this immediately.    Instead I want to make some changes, of which https://github.com/jeffreykegler/libmarpa/commit/1c8d868d83266b6292c21decc576c2d7a9d5d4ce and https://github.com/jeffreykegler/libmarpa/commit/af9567fdbb35d6753f143dc1313f6973b3a17bd0 are the first two, and ask how the code works after the changes.

**Comment by dabrahams** [comment] 2022-05-22 02:40
@jeffreykegler What are the packaging-developer instructions?  The homebrew formula ought to be able to use those; presumably that would drastically cut down this [list of dependencies](https://github.com/Homebrew/homebrew-core/blob/64a41894941197f1c7b11c2f591a101484efc9ae/Formula/libmarpa.rb#L19-L25)!

**Comment by jddurand** [comment] 2022-05-22 09:59
IMHO the version of libmarpa to use is the one that is packaged and, as far I know, it exist only in perl's Marpa--R2 (that is on github). Then the library is to be compiled using these source files:

```FILE (GLOB lib_marpa_src "${MARPA__R2_DIR}/cpan/engine/read_only/*.c")```

**Comment by jeffreykegler** [comment] 2022-05-22 15:09
Libmarpa creates an autoconf and a CMake distribution, so the instructions are those for autoconf or CMake.  Every official release will be in the form of an autoconf and a CMake distro, will contain only the .c files, not the original CWeb, and will not require installation of CWeb or TeX.

Usually the target would be a shared library installation, but currently this is not really useful for Libmarpa, because every binary has a unique version of Libmarpa, so no memory is saved.  My thought is that there is currently no point in putting Libmarpa directly into the root hierarchy.

The target in Marpa::R2's case is a Perl module.  To do this an autoconf distro is untar'd into the Marpa::R2 development hierarchy, and it is built.  Libmarpa could be installed relative to the Marpa::R2 development hierarchy, but IIRC Marpa::R2 simply grabs the files it needs from the Marpa::R2/Libmarpa build hierarchy.  (The files needed are the static version of the Libmarpa library and the public header, `marpa.h`.)

[Above](https://github.com/jeffreykegler/libmarpa/issues/110#issuecomment-1133860803) Jean-Damien (who has a lot of experience taking Libmarpa downstream) mentions he finds the best place to grab the Marpa::R2 autoconf distro is from the Marpa::R2 code.  That's certainly a well-tested version.  I've done a lot of work with the Libmarpa release discipline since Jean-Damien started his work, and plan to do a lot more, so things may improve, and soon Jean-Damien may have a better alternative.

Of course, if you're doing me the favor of following my Libmarpa internals development closely, you are forced to clone the Libmarpa repo and build the autoconf or CMake distro, and this *does* require CWeb, etc.

> @jeffreykegler What are the packaging-developer instructions? The homebrew formula ought to be able to use those; presumably that would drastically cut down this [list of dependencies](https://github.com/Homebrew/homebrew-core/blob/64a41894941197f1c7b11c2f591a101484efc9ae/Formula/libmarpa.rb#L19-L25)!

**Comment by jeffreykegler** [comment] 2022-05-22 15:13
> Makes sense. I'll probably explore the package maintainer route when I have a full handle on things. Feel free to close this issue, since it looks like the previous one is tracking a similar issue.

I've made changes in the current head of the "tested" branch: 30a3ea8f3b41e14408cef11d4aa8efe818633b96.  @mpope9: Perhaps you could try them and let me know if they fix the issues?

**Comment by mpope9** [comment] 2022-05-22 16:27
Still seeing the issue on tested:
```

**Comment by jeffreykegler** [comment] 2022-05-22 18:11
I wonder what version of Cmake you are running?  I am at "cmake version 3.13.4".  There is in fact, no project() command in `test/CMakelists.txt`, as your cmake complains, but my version does not see that as a problem.

**Comment by mpope9** [comment] 2022-05-22 18:19
```
>cmake --version
cmake version 3.22.1
```

So slightly newer it seems. This is what is installed by the latest Ubuntu with `apt install`.

**Comment by jeffreykegler** [comment] 2022-05-22 18:57
From the 3.22 cmake(1) page: "The source tree must contain a CMakeLists.txt file and must not contain a CMakeCache.txt file because the latter identifies an existing build tree."  Does your "test" directory contain a `CMakeCache.txt ` file?  If so, deleting it may be the fix.

In any case, the failing cmake command in https://github.com/jeffreykegler/libmarpa/issues/110#issuecomment-1133930120 is confused about source and build directories.  In my set up, it realizes they are separate.  In [your output](https://github.com/jeffreykegler/libmarpa/issues/110#issuecomment-1133930120), cmake has decided source and build directories are identical, which I forbid.  I am going to change the failing cmake  command to be explicit about the build and source directories.

I will let you know when I have made that fix.

**Comment by jeffreykegler** [comment] 2022-05-22 19:29
I made a few improvement to the CMakeLists.txt files, including adding the project() command that the warning squawked about, and explicit source and build directories.  They are in commit e33b280355569f7817dd013409b702a3b5c99c0e, at the head of the "tested" branch.

**Comment by mpope9** [comment] 2022-05-22 19:33
I can take it out for a spin in an hour or so, will report back.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by mpope9** [comment] 2022-05-23 02:30
Looks good!

**Comment by jeffreykegler** [comment] 2022-05-28 12:33
Closed per https://github.com/jeffreykegler/libmarpa/issues/110#issuecomment-1134897570.

**Closed by jeffreykegler** 2022-05-28 12:33 UTC
Labels: About to be closed
