### ISSUE TITLE
Infinite loop in marpa_t_next

### ISSUE THREAD

**Issue by dabrahams** [jeffreykegler/libmarpa#116] opened 2022-05-30 04:27 UTC
[Reproducer](https://gist.github.com/dabrahams/ea0d446e56e7b4469d871ee30b323118) is not small, sorry.

**Comment by jeffreykegler** [comment] 2022-05-30 11:18
Is it possible I'd be able to reproduce this on my Raspberry Pi?  Is everything open source?

**Comment by dabrahams** [comment] 2022-05-30 13:01
Yes, everything is open source. Check out the “parser” branch of https://github.com/val-lang/val and run “swift test” in the root.

**Comment by jeffreykegler** [comment] 2022-05-30 16:31
That's done, but it tells me I need swift.  There is a Debian swift package, but I think it's something else.  In any case, you probably have a specific version repo you suggest.

FYI, I'm a total Swift newbie, so expect dumb questions. :-)

**Comment by dabrahams** [comment] 2022-05-30 17:09
https://www.swift.org/download/ <https://www.swift.org/download/> if you want to do it with Swift. I’m going on vacation for 2 weeks, so won’t be around to answer questions during that time.  I would guess you would have an easier time reproducing by translating the grammar/regexps from the gist into Marpa::R2, though.

The regexps are in ICU regex format, and most of them aren’t even used in that example.

**Comment by dabrahams** [comment] 2022-05-30 17:44
The token sequence, if you want to avoid the regexps, is:

> 'type' hspace identifier hspace '{' newlines hspace 'fun' identifier '(' ')' hspace '{' '}' newlines hspace '}' newlines hspace 'extension' hspace identifier hspace '{' newlines hspace 'fun' hspace identifier '(' ')' hspace '{' '}' newlines hspace '}'

**Comment by jeffreykegler** [comment] 2022-05-30 17:55
Have a good vacation. It may allow me to catch up some of these issues. :-)

I'll think about the Marpa::R2 translation. Definitely a better developed debugging environment, but the translation might be hard. I notice some new syntax in your BNF,and it is nice-looking, but an obstacle in this context. And there is the disadvantage that failure to duplicate under Marpa::R2 is not really very good evidence of anything.

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by jeffreykegler** [comment] 2022-05-30 17:56
The token sequence is very very helpful.  Is it convenient to do it for issue #115 also?

**Comment by dabrahams** [comment] 2022-05-30 18:35
I can try.  Note that the two grammars are different.

**Comment by jeffreykegler** [comment] 2022-06-01 16:12
I converted the grammar to Marpa::R2's SLIF.  There is a problem with it ("unproductive symbols"), which causes warnings, but despite the warnings in R2 the parse goes through without incident.  I produced a parse tree, and it looks like what would be expected.  Here is the Perl test script: https://github.com/jeffreykegler/Marpa--R2/blob/68c05b0fb4719d571906ebfe6104c2544f00d627/cpan/sl_lib116.t.  I tested with both Libmarpa in the current official release, and with the [bleeding edge commit](03e3248ea0ca6838fc1d663935d34010c6da7ec8),  with identical results.

The problem which causes the warning is here: https://github.com/jeffreykegler/Marpa--R2/blob/68c05b0fb4719d571906ebfe6104c2544f00d627/cpan/sl_lib116.t#L503.  `trait__composition_1__list`'s only rule is a left-recursive, which makes `trait__composition_1__list`, and several other symbols which require it on the RHS, unproductive.  I've added a comment showing a rule that would fix the warnings.

This recursion might seem to explain the infinite loop, except that Libmarpa excises unproductive rules from the grammar for precisely this reason.  If the "unproductivity" propagates back to the start symbol, precomputation fails, but otherwise you can go ahead with what remains of the grammar, which is what I was able to do with Marpa::R2.  Why this failed in the reported setup is, I confess, a bit of a mystery to me.

**Comment by dabrahams** [comment] 2022-06-01 21:39
> Have a good vacation. It may allow me to catch up some of these issues. :-) 

Thanks.  I was working rather obsessively on my own implementation of this stuff through the plane ride [here](https://github.com/dabrahams/smarpa/blob/main/Sources/smarpa/Grammar.swift) and [here](https://github.com/dabrahams/smarpa/blob/main/Sources/smarpa/Parser.swift) yesterday.  Now I am going to rest and leave it alone for a while.

I do see now, why scan should come first and not last (as it does in my implementation).

I'm not very pleased with the way I store Leo items, and was thinking of putting them directly into the same array as Earley items, burning storage for a single symbol per Earley item for the unused transition symbol.  Earley items are just 3 `Int`s right now and could be compressed further to make room for that symbol… or, perhaps better, storing an Earley item's postdot symbol there to improve locality.

Other thoughts about efficiency: I realize I am doing lots of linear searches, but the length of these searches is so short, and in contiguous memory, that I suspect it's hard to improve upon.  It seems to me that to maintain strict big-O guarantees it might make sense to introduce a “slow path” that kicks in over some constant size, using algorithms with better complexity bounds.

**Comment by dabrahams** [comment] 2022-06-02 00:10
When I get back from break I can probably make you a log of the sequence of marpa_xxxx calls and their parameters

**Comment by jeffreykegler** [comment] 2022-06-03 16:09
@dabrahams I hope you'll be ignoring all my issue updates until you are back from vacation and caught up.  None of them will have your feedback on a critical path.

I'd stop making the updates, except they are vital for my own tracking of the issues, and also there may be 3rd parties out there following these.

**Comment by jeffreykegler** [comment] 2022-06-04 19:42
Using the more careful approach I used in #115, I re-attempted to duplicate this issue, and again cannot duplicate it.  The script is [ here](https://github.com/jeffreykegler/Marpa--R2/blob/80be1a259e134fd8c6542e6d125ee574a5b35702/cpan/sl_lib116.t).  It parses to the tree show in https://github.com/jeffreykegler/Marpa--R2/blob/80be1a259e134fd8c6542e6d125ee574a5b35702/cpan/sl_lib116.t#L809-L847.

**Comment by jeffreykegler** [comment] 2022-06-11 16:07
Two conjectures:  First, I conjecture that this is the same problem that I have identified for #115.  See https://github.com/jeffreykegler/libmarpa/issues/115#issuecomment-1152954497 and its preceding comments.  I conjecture that this is not actually an infinite loop, but the tree logic rejecting all of an exponentially long series of parses.

Second, the failure to duplicate is due to my not having the right sequence of lexemes.  This grammar is ridiculously liberal in what it allows with whitespace, so the lexer can represent the same input string with many different lexeme sequences.

If these two conjectures are right, and my proposed solution to #115 works, that solution should also fix this problem.  I plan to continue work on #115.

**Comment by dabrahams** [comment] 2022-06-14 16:02
In support of your conjecture that there's an exponentially long series of parses, I had a grammar that was appearing to exhibit this behavior, then upgraded to the latest tested libmarpa, and started getting ambiguity reports rather than apparent hangs.

**Comment by jeffreykegler** [comment] 2022-06-14 17:48
@dabrahams Can I read your last comment ( https://github.com/jeffreykegler/libmarpa/issues/116#issuecomment-1155398661) as saying this issue is fixed?

**Comment by jeffreykegler** [comment] 2022-06-14 18:28
If you prefer to wait a bit in order to check more carefully that this issue has really gone away, that is a good thing, and I will wait.

**Comment by jeffreykegler** [comment] 2022-06-14 20:15
There is a fix which has eliminated the issue, and the connection is not just "post hoc ergo propter hoc".  We have an explanation of why the fix for #115 was expected to fix this issue (a prediction in fact) and several tests for #115.

I have also a proof of completeness and consistency of the new code for detecting or-node cycles, to help us assure ourselves that the fix for #115 does address all issues related to or-node cycle testing, and does not open up any new ones.  That is, the proof shows the fix does eliminate all or-node cycles, and does not eliminate any trees that do not contain or-node cycles. (I'll shortly write a comment in #115 pointing to the proof, which is in the CWeb code.)

Absent feedback to the contrary, I will close this issue in a couple of days.

Of course, if this, or similar, issues appear with the new version of Libmarpa, we can reopen this, or open a new issue, as appropriate.

**Comment by jeffreykegler** [comment] 2022-06-14 23:25
There an apparent memory issue with the fix to #115: https://github.com/jeffreykegler/libmarpa/issues/115#issuecomment-1155795245.  Since two issues seem to be related, I am stopping the "close countdown" on this issue until it is resolved.

**Comment by jeffreykegler** [comment] 2022-06-15 20:56
Commit https://github.com/jeffreykegler/libmarpa/commit/25eb1da3a1c7d0d4db029bb0306eec7d42c4e9e2, which is the head of the "tested" branch, has a new fix for this and #115, without the memory issue.

**Comment by jeffreykegler** [comment] 2022-06-22 16:02
I never did duplicate this, and I see no reason to do so now if the problem has gone away.  There's no guarantee I'd succeed, and the time is, I think, better invested elsewhere.

@dabrahams Has the problem gone away?  Any reason to keep this open?

**Comment by dabrahams** [comment] 2022-06-22 16:10
The problem doesn't reproduce with a more recent libmarpa and that exact test case.

**Comment by jeffreykegler** [comment] 2022-06-22 16:13
Per https://github.com/jeffreykegler/libmarpa/issues/116#issuecomment-1163319357 and https://github.com/jeffreykegler/libmarpa/issues/116#issuecomment-1163305674, and absent feedback to the contrary, I will close this issue after a couple of days.

**Comment by jeffreykegler** [comment] 2022-06-28 00:22
Closed as per https://github.com/jeffreykegler/libmarpa/issues/116#issuecomment-1163324099.

**Closed by jeffreykegler** 2022-06-28 00:22 UTC
Labels: About to be closed
